config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'
  get '/toppages', :to => 'toppages#show'
  devise_for :users, controllers: { registrations: 'registrations' }

  resources :weights, except: [:index]
  post '/remotes', :to => 'remotes#create'

  resources :profiles, only: [:show, :new, :create, :edit, :update, :destroy]
  resources :weightodons, only: [:show, :new, :create, :update, :destroy]
end

app/models/weight.rb
class Weight < ApplicationRecord
  belongs_to :user

  validates :user_id, presence: true
  validates :value, presence: true, numericality: true
  validates :date, presence: true
end

app/controllers/weights_controller.rb
class WeightsController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user, only: [:destroy]

  def show
    @weight = Weight.find(params[:id])
  end

  def new
    @weight = Weight.new
  end

  def create
    @weight = current_user.weights.build(weight_params)
    if @weight.save

      send_weightodon(current_user, @weight.value)

      flash[:notice] = '体重を投稿しました。'
    else
      @weights = current_user.weights.page(params[:page]).per(14)
      flash[:alert] = '体重の投稿に失敗しました。'
    end
    redirect_to root_url
  end

  def edit
    @weight = Weight.find(params[:id])
  end

  def update
    @weight = Weight.find(params[:id])

    if @weight.update(weight_params)
      flash[:notice] = '正常に更新されました。'
    else
      flash.now[:alert] = '正常に更新されませんでした。'
      render :edit
    end

    redirect_to root_url
  end

  def destroy
    @weight.destroy
    flash[:notice] = '体重を削除しました。'
    redirect_to root_url
  end

  private

  def weight_params
    params.require(:weight).permit(:value, :date)
  end

  def correct_user
    @weight = current_user.weights.find_by(id: params[:id])
    unless @weight
      redirect_to root_url
    end
  end
end

app/views/weights/_form.html.erb
<div class="row">
  <div class="col s4">
  <%= form_for(weight) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>

      <%= f.label :value, '体重' %>
      <%= f.text_field :value, class: 'form-control' ,:autocomplete => :off%>

      <%= f.label :date, '日時' %>
      <%= f.datetime_field :date, value: Time.now.strftime("%Y-%m-%dT%H:%M") %>

      <%= f.submit '投稿', class: 'waves-effect waves-light btn orange' %>
      <%= link_to 'キャンセル', root_path, class: 'waves-effect waves-light btn grey' %>
  <% end %>
  </div>
</div>

app/views/weights/edit.html.erb
<h1>体重編集</h1>

<%= render 'form', weight: @weight %>

app/views/weights/new.html.erb
<h3>体重投稿</h3>

<%= render 'form', weight: @weight %>

app/views/weights/show.html.erb
<h1>id: <%= @weight.id %> の詳細ページ</h1>

<p><%= @weight.created_at %></p>
<p><%= @weight.value %> kg</p>

<%= link_to '一覧に戻る', weights_path %>
<%= link_to '編集する', edit_weight_path(@weight) %>
<%= link_to '削除する', @weight, method: :delete, data: { confirm: '本当に削除してよろしいですか？' } %>