config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'
  get '/toppages', :to => 'toppages#show'
  devise_for :users, controllers: { registrations: 'registrations' }

  resources :weights, except: [:index]
  post '/remotes', :to => 'remotes#create'

  resources :profiles, only: [:show, :new, :create, :edit, :update, :destroy]
  resources :weightodons, only: [:show, :new, :create, :update, :destroy]
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
    if user_signed_in?
      @user = current_user
      @weights = current_user.weights.page(params[:page]).per(14)
      @profile = current_user.profile

      if mastodon_connected?(current_user)
        @weightodon = current_user.weightodon
        @account = valid_account?(@weightodon.access_token)
      end

      if @weights and @weights.first
        @latest_weight = @weights.first.value
      else
        @latest_weight = @profile.start_weight
      end

      if params[:duration] == "all"
        @graph_weights = current_user.weights.pluck(:value)
        @graph_date = current_user.weights.pluck(:date).map{|date| date.strftime("%m/%d")}
      elsif params[:duration] == "3month"
        @graph_weights = current_user.weights.pluck(:value).take(90)
        @graph_date = current_user.weights.pluck(:date).map{|date| date.strftime("%m/%d")}.take(90)
      elsif params[:duration] == "month"
        @graph_weights = current_user.weights.pluck(:value).take(30)
        @graph_date = current_user.weights.pluck(:date).map{|date| date.strftime("%m/%d")}.take(30)
      else
        @graph_weights = current_user.weights.pluck(:value).take(7)
        @graph_date = current_user.weights.pluck(:date).map{|date| date.strftime("%m/%d")}.take(7)
      end

      @graph_weights.reverse!
      @graph_date.reverse!
    else
      @welcome = true
      @profiles = Profile.where(public: "公開").order("updated_at DESC").limit(3)
    end
  end

  def show
    @user = User.find(params[:id])
    @weights = @user.weights.page(params[:page]).per(14)
    @profile = @user.profile

    if mastodon_connected?(@user)
      @weightodon = @user.weightodon
      @account = valid_account?(@weightodon.access_token)
    end

    if @weights and @weights.first
      @latest_weight = @weights.first.value
    else
      @latest_weight = @profile.start_weight
    end

    if params[:duration] == "all"
      @graph_weights = @user.weights.pluck(:value)
      @graph_date = @user.weights.pluck(:date).map{|date| date.strftime("%m/%d")}
    elsif params[:duration] == "3month"
      @graph_weights = @user.weights.pluck(:value).take(90)
      @graph_date = @user.weights.pluck(:date).map{|date| date.strftime("%m/%d")}.take(90)
    elsif params[:duration] == "month"
      @graph_weights = @user.weights.pluck(:value).take(30)
      @graph_date = @user.weights.pluck(:date).map{|date| date.strftime("%m/%d")}.take(30)
    else
      @graph_weights = @user.weights.pluck(:value).take(7)
      @graph_date = @user.weights.pluck(:date).map{|date| date.strftime("%m/%d")}.take(7)
    end

    @graph_weights.reverse!
    @graph_date.reverse!
  end
end

app/views/toppages/_dashboard.html.erb
<div class="row">
  <% if user_signed_in? %>
  <div class="fixed-action-btn">
    <a class="btn-floating btn-large red" href="/weights/new">
      <i class="large material-icons">mode_edit</i>
    </a>
  </div>
  <% end %>

  <aside class="col s4">

    <%= render :template => 'profiles/show' %>

    <% if user_signed_in? %>
      <%= render :template => 'weightodons/show' %>
    <% else %>
      <% if @account %>
        マストドンもフォローしてね！ <a href="<%= @account.url %>" target="_blank">@<%= @account.username %></a>
      <% end %>
    <% end%>

    </aside>
    <div class="col s8">
      
    <br/>

    <% if user_signed_in? %>
      <a class='dropdown-trigger right black-text' href='#' data-target='dropdown1'><i class="material-icons">menu</i></a>

      <ul id='dropdown1' class='dropdown-content'>
        <li><%= link_to 'プロフィール編集', edit_profile_path(@profile), data: {turbolinks: false},class: 'right'%></li>

        <% if mastodon_connected? %>
          <li><%= link_to 'マストドン連携解除', current_user.weightodon,
                          method: :delete, data: { confirm: '本当に解除してよろしいですか？' } %></li>
        <% else %>
          <li><%= link_to 'マストドン連携', new_weightodon_path %></li>
        <% end %>
        <li><%= link_to 'トークン発行', current_user.profile ,
                        method: :delete, data: { confirm: '既存のトークンは破棄され、新しいトークンを生成します。' } %></li>
      </ul>
    <% end %>

    <ul class="tabs">
      <% if user_signed_in? %>
        <li class="tab col s3"><%= link_to '7days', root_path(duration: "week") %></li>
        <li class="tab col s3"><%= link_to '30days', root_path(duration: "month") %></li>
        <li class="tab col s3"><%= link_to '90days', root_path(duration: "3month") %></li>
        <li class="tab col s3"><%= link_to 'All', root_path(duration: "all") %></li>
      <% else %>
        <li class="tab col s3"><%= link_to '7days', toppages_path(id: @profile.user_id, duration: "week") %></li>
        <li class="tab col s3"><%= link_to '30days', toppages_path(id: @profile.user_id, duration: "month") %></li>
        <li class="tab col s3"><%= link_to '90days', toppages_path(id: @profile.user_id, duration: "3month") %></li>
        <li class="tab col s3"><%= link_to 'All', toppages_path(id: @profile.user_id, duration: "all") %></li>
      <% end %>
    </ul>

    <%= render 'graph' %>

    <table class="striped">
      <thead>
      <tr>
        <th>Date</th>
        <th>Weight</th>
        <% if user_signed_in? %>
          <th>Action</th>
        <% end %>
      </tr>
      </thead>
      <tbody>
      <% @weights.each do |weight| %>
        <tr>
          <td><%= weight.date.strftime('%Y-%m-%d %H:%M') %></td>
          <td><%= weight.value %> kg</td>
          <% if user_signed_in? %>
            <td>
              <i class="tiny material-icons">edit</i>
              <%= link_to '編集', edit_weight_path(weight) %>
              <i class="tiny material-icons">delete</i>
              <%= link_to '削除', weight, method: :delete, data: { confirm: '本当に削除してよろしいですか？' } %>
            </td>
          <% end %>
        </tr>
      <% end %>
      </tbody>
    </table>
    <%= paginate @weights %>

    <%= render 'google_adsense' %>
  </div>
</div>

app/views/toppages/_dashboard_mobole.html.erb
<div class="row">
  <% if user_signed_in? %>
    <div class="fixed-action-btn">
      <a class="btn-floating btn-large red" href="/weights/new">
        <i class="large material-icons">mode_edit</i>
      </a>
    </div>
  <% end %>

  <div class="col s12">

  <%= render :template => 'profiles/show' %>

  <% if user_signed_in? %>
    <%= render :template => 'weightodons/show' %>
  <% else %>
    <% if @account %>
      マストドンもフォローしてね！ <a href="<%= @account.url %>" target="_blank">@<%= @account.username %></a>
    <% end %>
  <% end%>

  </div>
  <div class="col s12">

  <br/>

  <% if user_signed_in? %>
    <a class='dropdown-trigger right black-text' href='#' data-target='dropdown1'><i class="material-icons">menu</i></a>

    <ul id='dropdown1' class='dropdown-content'>
      <li><%= link_to 'プロフィール編集', edit_profile_path(@profile), data: {turbolinks: false},class: 'right'%></li>

      <% if mastodon_connected? %>
        <li><%= link_to 'マストドン連携解除', current_user.weightodon,
                        method: :delete, data: { confirm: '本当に解除してよろしいですか？' } %></li>
      <% else %>
        <li><%= link_to 'マストドン連携', new_weightodon_path %></li>
      <% end %>
      <li><%= link_to 'トークン発行', current_user.profile ,
                      method: :delete, data: { confirm: '既存のトークンは破棄され、新しいトークンを生成します。' } %></li>
    </ul>
  <% end %>

  <ul class="tabs">
    <% if user_signed_in? %>
      <li class="tab col s3"><%= link_to '7days', root_path(duration: "week") %></li>
      <li class="tab col s3"><%= link_to '30days', root_path(duration: "month") %></li>
      <li class="tab col s3"><%= link_to '90days', root_path(duration: "3month") %></li>
      <li class="tab col s3"><%= link_to 'All', root_path(duration: "all") %></li>
    <% else %>
      <li class="tab col s3"><%= link_to '7days', toppages_path(id: @profile.user_id, duration: "week") %></li>
      <li class="tab col s3"><%= link_to '30days', toppages_path(id: @profile.user_id, duration: "month") %></li>
      <li class="tab col s3"><%= link_to '90days', toppages_path(id: @profile.user_id, duration: "3month") %></li>
      <li class="tab col s3"><%= link_to 'All', toppages_path(id: @profile.user_id, duration: "all") %></li>
    <% end %>
  </ul>

  <%= render 'graph' %>

  <table class="striped">
    <thead>
    <tr>
      <th>Date</th>
      <th>Weight</th>
      <% if user_signed_in? %>
        <th>Action</th>
      <% end %>
    </tr>
    </thead>
    <tbody>
    <% @weights.each do |weight| %>
      <tr>
        <td><%= weight.date.strftime('%Y-%m-%d %H:%M') %></td>
        <td><%= weight.value %> kg</td>
        <% if user_signed_in? %>
          <td>
            <i class="tiny material-icons">edit</i>
            <%= link_to '編集', edit_weight_path(weight) %>
            <i class="tiny material-icons">delete</i>
            <%= link_to '削除', weight, method: :delete, data: { confirm: '本当に削除してよろしいですか？' } %>
          </td>
        <% end %>
      </tr>
    <% end %>
    </tbody>
  </table>
  <%= paginate @weights %>

  <%= render 'google_adsense' %>
  </div>
</div>

app/views/toppages/_google_adsense.html.erb
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- weightodon -->
<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-8186728334774578"
     data-ad-slot="1180897530"
     data-ad-format="auto"
     data-full-width-responsive="true"></ins>
<script>
    (adsbygoogle = window.adsbygoogle || []).push({});
</script>

app/views/toppages/_graph.html.erb
<canvas id="myChart"></canvas>
<script>
  var ctx = document.getElementById("myChart").getContext('2d');
  var chart = new Chart(ctx, {
      type: 'line',
      data: {
          labels: <%= raw @graph_date %>,
          datasets: [{
              label: "weight",
              data: <%= raw @graph_weights %>,
              backgroundColor: 'rgba(255, 99, 132, 1.0)',
              borderColor: 'rgba(255, 50, 132, 1.0)',
              fill: false
          }]
      },
  });
</script>

app/views/toppages/_welcome.html.erb
<!--<a href="https://github.com/tsu-nera/weightodon"><img style="position: absolute; top: 0; right: 0; border: 0;" src="https://s3.amazonaws.com/github/ribbons/forkme_right_orange_ff7600.png" alt="Fork me on GitHub"></a>-->

<div id="fullpage">

  <div class="section part1">
    <div class="container">
    <div class="no-pad-bot" id="index-banner">
      <h1 class="header right-align orange-text">WeightoDon</h1>
      <div class="row center">
        <h5 class="header col s12 light white-text right-align">スマートな体重記録サイト</h5>
        <h5 class="header col s12 light white-text right-align">A smart weight recording site connected with Mastodon</h5>
      </div>
      <div class="row right-align">
        <%= link_to 'Sign up', new_user_registration_path, class: 'btn-large waves-effect waves-light orange'%>
        <%= link_to 'Login', new_user_session_path, class: 'btn-large waves-effect waves-light orange'%>
      </div>
    </div>
  </div>
  </div>

  <div class="section part2">
    <div class="container">
    <h4 class="center header light">多彩な連携機能</h4>

      <div class="row">
        <div class="col s12 m4">
          <div class="icon-block">
            <h2 class="center light-blue-text hide-on-small-only"><i class="material-icons">group</i></h2>
            <h5 class="center">Mastodon</h5>

            <p class="light">Twitterのクローンであるマストドンと連携できます。ソーシャルメディアに自分の体重を晒すのに抵抗がある人は安心してください。完全匿名性のコミュニティをあなたのために用意しています。</p>
          </div>
        </div>

        <div class="col s12 m4">
          <div class="icon-block">
            <h2 class="center light-blue-text hide-on-small-only"><i class="material-icons">flash_on</i></h2>
            <h5 class="center">Smart Scales</h5>

            <p class="light">スマート体重計からの体重自動入力をサポートします。体重記録でもっとも煩わしい作業は、体重をスマホから入力することでした。WeightoDonとスマート体重計を連携させることで、その入力作業は自動化できます。</p>
          </div>
        </div>

        <div class="col s12 m4">
          <div class="icon-block">
            <h2 class="center light-blue-text hide-on-small-only"><i class="material-icons">chat</i></h2>
            <h5 class="center">Smart Speakers</h5>

            <p class="light">スマートスピーカーからの音声入力をサポートします。お風呂あがりやワークアウトのあとなど、スマホを直接操作できないときも大丈夫。スマートスピーカーに話しかけるだけで体重記録ができます。</p>
          </div>
      </div>
    </div>
    <div class="center hide-on-small-only">
      <%= link_to 'もっと詳しく', "https://github.com/tsu-nera/weightodon/wiki", class: 'btn-large waves-effect waves-light orange', target: '_blank' %>
    </div>
  </div>
  </div>

  <div class="section part3">
    <div class="container">
      <h4 class="center header light">特徴</h4>
      <div class="row">
        <div class="col m8 offset-m2 s12">
          <% if browser.device.mobile? %>
            <h6 class="light"><i class="material-icons light-blue-text">check_box</i>全て無料のオープンソース</h6>
            <h6 class="light"><i class="material-icons light-blue-text">check_box</i>完全に匿名なマストドンコミュニティ</h6>
            <h6 class="light"><i class="material-icons light-blue-text">check_box</i>直感的にわかりやすいUIと体重投稿機能</h6>
            <h6 class="light"><i class="material-icons light-blue-text">check_box</i>見やすいダッシュボードと体重グラフ表示</h6>
            <h6 class="light"><i class="material-icons light-blue-text">check_box</i>マストドンと連携した体重投稿をサポート</h6>
            <h6 class="light"><i class="material-icons light-blue-text">check_box</i>スマート体重計からの自動入力をサポート</h6>
            <h6 class="light"><i class="material-icons light-blue-text">check_box</i>スマートスピーカーからの音声入力をサポート</h6>
            <% else %>
            <h5 class="light"><i class="material-icons light-blue-text">check_box</i>全て無料のオープンソース</h5>
            <h5 class="light"><i class="material-icons light-blue-text">check_box</i>完全に匿名なマストドンコミュニティ</h5>
            <h5 class="light"><i class="material-icons light-blue-text">check_box</i>直感的にわかりやすいUIと体重投稿機能</h5>
            <h5 class="light"><i class="material-icons light-blue-text">check_box</i>見やすいダッシュボードと体重グラフ表示</h5>
            <h5 class="light"><i class="material-icons light-blue-text">check_box</i>マストドンと連携した体重投稿をサポート</h5>
            <h5 class="light"><i class="material-icons light-blue-text">check_box</i>スマート体重計からの自動入力をサポート</h5>
            <h5 class="light"><i class="material-icons light-blue-text">check_box</i>スマートスピーカーからの音声入力をサポート</h5>
            <% end %>
        </div>
      </div>
  </div>
  </div>

  <div class="section part4">
    <div class="container">
      <div class="row">
        <div class="col m8 offset-m2 s12">
          <h4 class="center header light white-text">仲間をつくり、励ましあう</h4>
          <div class="center">
          <%= link_to 'Go to Mastodon', "https://weightodon.site",
                      class: 'btn-large waves-effect waves-light orange', target: '_blank' %>
          </div>
          <table class="striped">
            <thead>
            <tr>
              <th class="white-text">ニックネーム</th>
              <th class="white-text">一言メッセージ</th>
            </tr>
            </thead>
            <tbody>
            <% @profiles.each do |profile| %>
              <tr>
                <td><%= link_to profile.nicname, toppages_path(id: profile.user_id), data: {"turbolinks" => false} %></td>
                <td><%= profile.message %></td>
              </tr>
            <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>

  <div class="section part5">
    <div class="container">
      <h4 class="center header light">さあ、はじめよう</h4>
      <br/>
      <div class="center">
        <%= link_to 'Join Now!', new_user_registration_path, id: "download-button", class: 'btn-large waves-effect waves-light orange' %>
      </div>
    </div>
  </div>
<!--    <hr width="800px">-->

<!--    <div class="container ">-->
<!--      <ul class="sns_button">-->
<!--        <li class="sns_button_twitter"></li>-->
<!--        <li class="sns_button_facebook"></li>-->
<!--        <li class="sns_button_hatena"></li>-->
<!--        <li class="sns_button_google"></li>-->
<!--        <li class="sns_button_line"></li>-->
<!--      </ul>-->
<!--    </div>-->
</div>

app/views/toppages/index.html.erb
<% if user_signed_in? %>
  <% if browser.device.mobile? %>
    <%= render 'dashboard_mobole'%>
  <% else %>
    <%= render 'dashboard'%>
  <% end %>
<% else %>
  <%= render 'welcome' %>
<% end %>

app/views/toppages/show.html.erb
<% if browser.device.mobile? %>
  <%= render 'dashboard_mobole'%>
<% else %>
  <%= render 'dashboard'%>
<% end %>